name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run eslint

      - name: Run unit tests
        run: npm run test-unit

      - name: Run Vue.js component tests
        run: npm test

      - name: Run React component tests
        run: npm run test-react

      - name: Run Svelte component tests
        run: npm run test-svelte
